homebrew_taps:
  - isen-ng/dotnet-sdk-versions
  - name: rhyeal/aws-rotate-iam-keys
    url: https://github.com/rhyeal/aws-rotate-iam-keys
  - azure/functions
  - fluxcd/tap
homebrew_installed_packages:
  - git
  - node
  - awscli
  - wget
  - git-flow-avh
  - aws-rotate-iam-keys
  - azure-cli
  - tfenv
  - azure-functions-core-tools
  - kubernetes-cli
  - helm
  - kube-ps1
  - kubectx
  - aws-iam-authenticator
  - flux
homebrew_cask_apps:
  - firefox
  - lastpass
  - docker
  - dotnet-sdk-2.2.400
  - sourcetree
  - mysqlworkbench