terraform_versions:
  - 0.12.29
  - 0.13.6
  - 0.14.6
terraform_providers:
  - name: terraform-provider-aws
    repository: https://github.com/hashicorp/terraform-provider-aws
    version: v3.28.0
    build_command: |
      cd tools \
      && go get github.com/hashicorp/go-getter \
      && go get -d github.com/pavius/impi/cmd/impi \
      && cd .. \
      && make tools \
      && make build
    install_dir: ~/.terraform.d/plugins/registry.terraform.io/hashicorp/aws/3.28.0/darwin_arm64
    install_name: terraform-provider-aws_v3.28.0_x5
  - name: terraform-provider-postgresql
    repository: https://github.com/cyrilgdn/terraform-provider-postgresql
    version: v1.11.1
    build_command: | 
      GOARCH=arm64 make build
    install_dir: ~/.terraform.d/plugins/registry.terraform.io/cyrilgdn/postgresql/1.11.1/darwin_arm64
    install_name: terraform-provider-postgresql_v1.11.1_x5