vscode_plugins:
  - alefragnani.bookmarks
  - bierner.markdown-mermaid
  - eamodio.gitlens
  - esbenp.prettier-vscode
  - fudge.auto-using
  - golang.go
  - hashicorp.terraform
  - kenhowardpdx.vscode-gist
  - ms-azure-devops.azure-pipelines
  - ms-azuretools.vscode-docker
  - ms-dotnettools.csharp
  - ms-python.python
  - ms-vscode-remote.remote-containers
  - ms-vscode.wordcount
  - msjsdiag.vscode-react-native
  - redhat.ansible
  - redhat.vscode-yaml
  - stkb.rewrap
