vscode_plugins:
  - ms-python.python
  - hashicorp.terraform
  - redhat.vscode-yaml
  - ms-azuretools.vscode-docker
  - ms-dotnettools.csharp
  - esbenp.prettier-vscode
  - alefragnani.bookmarks
  - msjsdiag.vscode-react-native
  - eamodio.gitlens
  - kenhowardpdx.vscode-gist
  - nikitakunevich.snippet-creator
  - ms-azure-devops.azure-pipelines
  - fudge.auto-using
  - cschleiden.vscode-github-actions
  - golang.go
  - ms-vscode-remote.remote-containers