---
- hosts: localhost
  connection: local
  vars_files:
     - vars/homebrew.yaml
     - vars/vscode-plugins.yaml
  vars:
    - user_name: "{{ ansible_user_id }}"
  tasks:
    - name: Install Rosetta
      shell:
        cmd: /usr/sbin/softwareupdate --install-rosetta --agree-to-license
      when: ansible_machine == 'arm64'
    - name: Install Homebrew packages
      import_role: 
        name: geerlingguy.homebrew
    - name: Install m1 specific apps
      when: ansible_machine == 'arm64'
      block:
        - name: Setup OSX install environment
          import_role:
            name: osx
        - name: Install Docker m1 preview
          import_role:
            name: './vendor/osx/osx/roles/installer'
          vars:
            app_name: Docker
            app_url: https://desktop.docker.com/mac/m1preview/Docker-AppleSilicon-Preview7.dmg
            installer_type: app
            install_method: dmg
            download_file_type: dmg
          tags:
            - docker
        - name: Install VS Code preview
          import_role:
            name: './vendor/osx/osx/roles/installer'
          vars:
            app_name: Visual Studio Code - Insiders
            app_url: https://code.visualstudio.com/sha/download?build=insider&os=darwin-arm64
            installer_type: app
            install_method: zip
            download_file_type: zip
        - name: OSX install cleanup
          import_role:
            name: './vendor/osx/osx/roles/cleanup'
        - name: Install tfenv from source
          shell:
            cmd: brew install --build-from-source tfenv
    - name: Install VS Code plugins
      block:
        - name: Set Code binary location
          set_fact:
            code_binary_path: "/usr/local/bin/{{ 'code-insiders' if ansible_machine == 'arm64' else 'code' }}"
            code_app_path: "/Applications/Visual Studio Code{{ ' - Insiders' if ansible_machine == 'arm64' else '' }}.app/Contents/Resources/app/bin/code"
        - name: Symlink Code binary
          file:
            src: "{{ code_app_path }}"
            dest: "{{ code_binary_path }}"
            state: link
        - name: Install VS Code extensions
          shell:
            cmd: "{{ code_binary_path }} --install-extension {{ item.name | default(item) }}"
          loop: "{{ vscode_plugins }}"
      tags:
        - vscode-ext
    - name: Install and configure oh-my-zsh
      import_role:
        name: gantsign.oh-my-zsh
      vars:  
        users:
          - username: "{{ user_name }}"
            plugins:
              - git
              - kube-ps1
              - vscode
    - name: "Create zsh profile file"
      file:
        path: ~{{ console_user | default(user_name) }}/.zshrc
        state: touch
    - name: "Add Kube_PS1 to zsh profile"
      lineinfile:
        dest: ~{{ console_user | default(user_name) }}/.zshrc
        line: "source {{ homebrew_install_path }}/Cellar/kube-ps1/0.7.0/share/kube-ps1.sh"
        regexp: source {{ homebrew_install_path }}/Cellar/kube-ps1/0.7.0/share/kube-ps1.sh
        state: present
    - name: Say All Done!
      osx_say:
        msg: "ALL DONE!"