---
- hosts: localhost
  connection: local
  vars_files:
     - vars/homebrew.yaml
  vars:
    - user_name: "{{ ansible_user_id }}"
  tasks:
    - name: Install Homebrew packages
      import_role: 
        name: geerlingguy.homebrew
    - name: Install and configure oh-my-zsh
      import_role:
        name: gantsign.oh-my-zsh
      vars:  
        users:
          - username: "{{ user_name }}"
            plugins:
              - git
              - kube-ps1
              - vscode
    - name: "Create zsh profile file"
      file:
        path: ~{{ console_user | default(user_name) }}/.zshrc
        state: touch
    - name: "Add Kube_PS1 to zsh profile"
      lineinfile:
        dest: ~{{ console_user | default(user_name) }}/.zshrc
        line: "source /usr/local/Cellar/kube-ps1/0.7.0/share/kube-ps1.sh"
        regexp: source /usr/local/Cellar/kube-ps1/0.7.0/share/kube-ps1.sh
        state: present
    - name: Say All Done!
      osx_say:
        msg: "ALL DONE!"