---
- hosts: localhost
  connection: local
  vars_files:
     - vars/homebrew.yaml
  vars:
    - user_name: jfeierman

  roles:
    - role: geerlingguy.homebrew
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ user_name }}"
          plugins:
            - git
            - kube-ps1
            - vscode

  tasks:
    - name: "Create bash profile file"
      file:
        path: ~{{ console_user | default(ansible_user) }}/.bash_profile
        state: touch
    - name: "Add Kube_PS1 to bash profile"
      lineinfile:
        dest: ~{{ console_user | default(ansible_user) }}/.bash_profile
        line: "source /usr/local/Cellar/kube-ps1/0.7.0/share/kube-ps1.sh"
        regexp: source /usr/local/Cellar/kube-ps1/0.7.0/share/kube-ps1.sh
        state: present
    - name: Say All Done!
      osx_say:
        msg: "ALL DONE!"